#!/bin/bash



logdate=$(date +"%Y%m%d")
logfile="$logdate"_report.log

cat <<- EOF > $logfile 

	This report was automatically generated by my Bash script.
	It contains a bries summary of some system information.

EOF


printf "SYS:\t%s\n" $MACHTYPE >> $logfile
printf "BASH:\t%s\n" $BASH_VERSION >> $logfile  
